name: CI
on: push
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Node 14
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      # Only update node modules when th lock file changes
      - name: Node cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Only update clojure deps when shadow-cljs.edn changes
      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/shadow-cljs.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install project dependencies
      - run: yarn install

      # Compile tests and run
      - run: npx shadow-cljs compile ci
      - run: npx karma start --single-run
